### ISSUE TITLE
🐛 Error when generating HTML responses

### ISSUE THREAD

**Issue by calumjs** [SSWConsulting/SSW.Rules.GPT#43] opened 2023-05-18 09:23 UTC
Cc:

Hi 

### Describe the Bug

I think it is dangerously setting innerhtml or something

### To Reproduce
Give a prompt like this:
Give me some html with inline JavaScript to display an alert with hello world inside

Got a weird white box with an error at the bottom of the screen
![Screenshot_20230518_191949_Chrome.jpg](https://github.com/SSWConsulting/SSW.Rules.GPT.Blazor/assets/13717390/9ddf5378-b577-401a-a330-896f660f4523)

### Expected Behavior

It returns the HTML in text form with no error

### Tasks
- [ ] Investigate
- [ ] Fix

### Environment
 - Device: galaxy fold 
 - Browser: Chrome
 - OS: Android

### Screenshots

Thanks!

**Comment by jackreimers** [comment] 2023-06-21 03:09
@calumjs is this still an issue? I can't reproduce it and the link to your screenshot is broken

**Comment by jackreimers** [comment] 2023-06-27 00:03
Resolved by #62

**Closed by jackreimers** 2023-06-27 00:03 UTC
Labels: Type: Bug
