### ISSUE TITLE
🐛 👤 Cancel Request covers output

### ISSUE THREAD

**Issue by Hona** [SSWConsulting/SSW.Rules.GPT#67] opened 2023-05-26 00:08 UTC
Cc: @MattParkerDev 

**Hi RulesGPT team,**

### Describe the Bug

There is a small UX problem where the cancel request button will cover output

![image](https://github.com/SSWConsulting/SSW.Rules.GPT/assets/10430890/94651825-7600-440e-89fb-71010168cece)

### Tasks
- [ ] Investigate
- [ ] Fix

### Environment
 - Device: [e.g. iPhone 12]
 - Browser: [e.g. chrome, safari]

### Screenshots

Thanks!

**Comment by MattParkerDev** [comment] 2023-05-26 00:10
Duplicate of #47

**Comment by jackreimers** [comment] 2023-06-07 06:32
Resolved by #47

**Closed by jackreimers** 2023-06-07 06:32 UTC
Labels: Type: Bug
